## Numpy array and basics


In [1]:
import numpy as np

### creating array from list

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr_2d)


1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [4]:
py_list = [1, 2, 3, 4, 5]
print("Python List multiplication :", py_list * 2)

np_array = np.array([1, 2, 3, 4, 5]) #element-wise multiplication
print("Numpy Array multiplication :", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n Python List Time:", time.time() - start)


start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy Array Time:", time.time() - start)



Python List multiplication : [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Numpy Array multiplication : [ 2  4  6  8 10]

 Python List Time: 0.034404754638671875

 Numpy Array Time: 0.0028247833251953125


### creatign array from scratch

In [ ]:
zeros = np.zeros((3, 4))
print("Zeros Array:\n", zeros)

ones = np.ones((2, 3))
print("Ones Array:\n", ones)

full = np.full((2, 2), 7) # 2*2 array filled with 7
print("Full Array:\n", full)

random = np.random.random((2, 3)) # 2*3 array with random values
print("Random Array:\n", random)

sequence = np.arange(0, 10, 2) # 1D array with values from 0 to 9 , 2 is the step(gap)
print("Sequence Array:", sequence)




Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Full Array:
 [[7 7]
 [7 7]]
Random Array:
 [[0.41450912 0.88195053 0.03171652]
 [0.44530847 0.20965901 0.34667667]]
Sequence Array: [0 2 4 6 8]


### Vector, Matrix and Tensor

In [27]:
vector = np.array([1, 2, 3]) # 1D array
print("Vector:", vector)

matrix = np.array([[1, 2], [3, 4]]) # 2D array
print("Matrix:\n", matrix)

tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # 3D array
print("Tensor:\n", tensor)

Vector: [1 2 3]
Matrix:
 [[1 2]
 [3 4]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array Properties

In [31]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array shape:\n", arr.shape)
print("Array dimensions:", arr.ndim)
print("Array size:", arr.size)
print("Array data type:", arr.dtype)

Array shape:
 (2, 3)
Array dimensions: 2
Array size: 6
Array data type: int64


### Array Reshaping

In [40]:
arr = np.arange(12)
print("Original Array:\n", arr)

reshaped = arr.reshape((3, 4)) # Reshape to 3 rows and 4 columns
print("Reshaped Array:\n", reshaped)

flattened = reshaped.flatten() # Flatten the array to 1D
print("Flattened Array:", flattened)

# ravel (returns view, instead of copy) it do not change the original array.
raveled = reshaped.ravel() # Return a contiguous flattened array
print("Raveled Array:", raveled)

# Transpose the array
transposed = reshaped.T # Transpose the array
print("Transposed Array:\n", transposed)


Original Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
