## Numpy Array Operatinos

In [4]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("Basic Slicing", arr[2:7]) # Slicing from index 2 to 6
print("step Slicing", arr[2:8:2]) # with gap of 2
print("Negative index", arr[-2]) 

Basic Slicing [3 4 5 6 7]
step Slicing [3 5 7]
Negative index 7


### 2D array slicing

In [ ]:
arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print("Sepecific element", arr_2d[2, 1]) # tell what is at the this index.
print("Entire row", arr_2d[0])
print("Entire row", arr_2d[1])
print("Entire row", arr_2d[2])
print("Entire col", arr_2d[:, 0]) # this is used to target the columns
print("Entire col", arr_2d[:, 1])
print("Entire col", arr_2d[:, 2])


Sepecific element 8
Entire row [1 2 3]
Entire row [4 5 6]
Entire row [7 8 9]
Entire col [1 4 7]
Entire col [2 5 8]
Entire col [3 6 9]


## Sorting

In [27]:
unsorted = np.array([3, 8, 7, 6, 8, 1])
print("Unsorted Array:", unsorted)
print("Unsorted Array:", np.sort(unsorted))


arr_2d_unsorted = np.array([[2, 1], [5, 2], [2, 3]])
print("Sorted 2d array by column:", np.sort(arr_2d_unsorted, axis=0)) #sorts cloumn 
print("Sorted 2d array by row:", np.sort(arr_2d_unsorted, axis=1)) #sorts row



Unsorted Array: [3 8 7 6 8 1]
Unsorted Array: [1 3 6 7 8 8]
Sorted 2d array by column: [[2 1]
 [2 2]
 [5 3]]
Sorted 2d array by row: [[1 2]
 [2 5]
 [2 3]]


### Filter

In [28]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8 , 9, 10])
even_numbers = numbers[numbers % 2 ==0]
print("Even Numbers:", even_numbers)

Even Numbers: [ 2  4  6  8 10]


## Filter with mask

In [29]:
mask = numbers > 5 
print("Numerbs greater than 5", numbers[mask])

Numerbs greater than 5 [ 6  7  8  9 10]


## Fancing indexing vs np.where()

In [ ]:
indices = [0, 2, 3, 4]
print(numbers[indices])

3 
where_result = np.where(numbers > 5)
print("NP where", numbers[where_result])


[1 3 4 5]
NP where [ 6  7  8  9 10]


In [ ]:
condition_array = np.where(numbers > 5, numbers * 2, numbers) # where is also used to declare array but with some conditions
# np.where(condition, value_if_true, value_if_false) hence the output will be, if number is > 5 then multiplied.
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


In [40]:
condition_array = np.where(numbers > 5, "true", "false")
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


In [ ]:
if (number > 5 ){
    numebers * 2
} else {
    numbers
}
# this is how we represent the above "where" conditon in If Else form.

### Adding and Removing Data

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combiined = arr1 + arr2
print(combiined)

combiined1 = np.concatenate((arr1, arr2))
print(combiined1)

[5 7 9]
[1 2 3 4 5 6]


### Arrya Compatibility

In [47]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
d = np.array([11,18,19,29])
print("Compatibility shapes:", a.shape == b.shape == c.shape)
print("Compatibility shapes:", a.shape == b.shape == c.shape == d.shape)

Compatibility shapes: True
Compatibility shapes: False


In [56]:
original = np.array([[1,2], [3,4]])
new_row = np.array([[5,6]])

result = np.vstack([original, new_row]) # add newrows


print(original) 
print("New array:", result)

new_col = np.array([[7],[8]])
result1 = np.hstack([original, new_col])
print("New Col:", result1)

[[1 2]
 [3 4]]
New array: [[1 2]
 [3 4]
 [5 6]]
New Col: [[1 2 7]
 [3 4 8]]


In [57]:
# Deletion of the array

array = np.array([1,2,3,4,5,6])
deleted = np.delete(array, 2)
print(deleted)

[1 2 4 5 6]
